import type { Metadata } from 'next'

import { Layout } from '@components/templates'
import Providers from './providers'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body style={{ overflow: 'hidden' }}>
				<Providers>
					<Layout>{children}</Layout>	
				</Providers>		
			</body>
		</html>
	)
}
